# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2
np.random.randint(0,100,(2,3,5))

array([[[ 5, 21, 41, 35, 45],
        [21, 49, 47, 37,  5],
        [54, 93, 59, 22, 99]],

       [[12, 33, 14,  1, 26],
        [23, 95, 71, 10, 87],
        [73, 70,  4,  4, 14]]])

In [5]:
# Method 3
np.random.uniform(0,100,(2,3,5))

array([[[ 4.40815433, 10.49214673, 45.92247606, 64.53814529,
         93.09705174],
        [12.49485274, 42.21686772, 36.68765905,  9.78883172,
         50.011094  ],
        [ 6.20632868, 48.08811601, 87.81516677, 70.38557634,
         69.45969573]],

       [[39.24238865, 99.18022732, 34.72782726, 90.30576875,
          5.5916366 ],
        [18.09169737, 34.15795759,  1.13017336,  4.09931701,
         69.52959965],
        [72.51891549, 42.93831833, 79.40789374, 28.53530376,
         12.17648402]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.46958627 0.55952076 0.25386546 0.2115137  0.89144831]
  [0.32000929 0.30421374 0.0688986  0.85140725 0.29758192]
  [0.59729965 0.01404536 0.70600863 0.06925215 0.93014788]]

 [[0.34046015 0.64459435 0.48098704 0.98228823 0.00445143]
  [0.76792705 0.78590023 0.93332911 0.9796564  0.97141482]
  [0.79836088 0.83595435 0.3851145  0.82720362 0.84563107]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
if a.size == b.size:
    print("True")
else:
    print("False")

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
# np.add(a,b)
print("No because they are not the same shape.")

No because they are not the same shape.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
# a = 2x3x5
# b = 5x2x3

c = b.reshape(2,3,5)

# c = np.transpose(b,(1,2,0)) also works


print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
# your code/answer here
# d = np.add(a,c)
d = a+c
print(d)
print("Now it works because they are the same shape")

[[[1.46958627 1.55952076 1.25386546 1.2115137  1.89144831]
  [1.32000929 1.30421374 1.0688986  1.85140725 1.29758192]
  [1.59729965 1.01404536 1.70600863 1.06925215 1.93014788]]

 [[1.34046015 1.64459435 1.48098704 1.98228823 1.00445143]
  [1.76792705 1.78590023 1.93332911 1.9796564  1.97141482]
  [1.79836088 1.83595435 1.3851145  1.82720362 1.84563107]]]
Now it works because they are the same shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a,"\n",d)
print("Yes, I see that a + 1 is the output of d")

[[[0.46958627 0.55952076 0.25386546 0.2115137  0.89144831]
  [0.32000929 0.30421374 0.0688986  0.85140725 0.29758192]
  [0.59729965 0.01404536 0.70600863 0.06925215 0.93014788]]

 [[0.34046015 0.64459435 0.48098704 0.98228823 0.00445143]
  [0.76792705 0.78590023 0.93332911 0.9796564  0.97141482]
  [0.79836088 0.83595435 0.3851145  0.82720362 0.84563107]]] 
 [[[1.46958627 1.55952076 1.25386546 1.2115137  1.89144831]
  [1.32000929 1.30421374 1.0688986  1.85140725 1.29758192]
  [1.59729965 1.01404536 1.70600863 1.06925215 1.93014788]]

 [[1.34046015 1.64459435 1.48098704 1.98228823 1.00445143]
  [1.76792705 1.78590023 1.93332911 1.9796564  1.97141482]
  [1.79836088 1.83595435 1.3851145  1.82720362 1.84563107]]]
Yes, I see that a + 1 is the output of d


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
if a.size == e.size:
    print("True")
else:
    print("False")

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9822882305282936
1.0044514339893924
1.570935740696307


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [26]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[1.46958627 1.55952076 1.25386546 1.2115137  1.89144831]
  [1.32000929 1.30421374 1.0688986  1.85140725 1.29758192]
  [1.59729965 1.01404536 1.70600863 1.06925215 1.93014788]]

 [[1.34046015 1.64459435 1.48098704 1.98228823 1.00445143]
  [1.76792705 1.78590023 1.93332911 1.9796564  1.97141482]
  [1.79836088 1.83595435 1.3851145  1.82720362 1.84563107]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [37]:
# your code here

# f[d > d_min] = 25 # not necessary
f[d < d_mean] = 25

f[d > d_mean] = 75
# f[d < d_max] = 75  # not necessary

f[d == d_mean] = 50

f[d == d_min] = 0
f[d == d_max] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [38]:
# your code here

print(d)
print("\n")
print(f)

[[[1.46958627 1.55952076 1.25386546 1.2115137  1.89144831]
  [1.32000929 1.30421374 1.0688986  1.85140725 1.29758192]
  [1.59729965 1.01404536 1.70600863 1.06925215 1.93014788]]

 [[1.34046015 1.64459435 1.48098704 1.98228823 1.00445143]
  [1.76792705 1.78590023 1.93332911 1.9796564  1.97141482]
  [1.79836088 1.83595435 1.3851145  1.82720362 1.84563107]]]


[[[ 25.  25.  25.  25.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  75.  25. 100.   0.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [48]:
# your code here

g = np.empty((2,3,5), dtype = str)

# f[d > d_min] = 25 # not necessary
g[d < d_mean] = "B"

g[d > d_mean] = "C"
# f[d < d_max] = 75  # not necessary

g[d == d_mean] = "D"

g[d == d_min] = "A"
g[d == d_max] = "E"

print(g)

[[['B' 'B' 'B' 'B' 'C']
  ['B' 'B' 'B' 'C' 'B']
  ['C' 'B' 'C' 'B' 'C']]

 [['B' 'C' 'B' 'E' 'A']
  ['C' 'C' 'C' 'C' 'C']
  ['C' 'C' 'B' 'C' 'C']]]
